### ISSUE TITLE
Adding Custom Domains to your Site

### ISSUE THREAD

**Issue by Tsukasa007** [Monogramm/docker-erpnext#19]
Thank you for your quick deployment.
Is there a quick way to add it?
I've tried this.  https://frappe.io/docs/user/en/bench/guides/adding-custom-domains
But it didn't work.!!!
help....

**Comment by madmath03** [comment]
Hello @Tsukasa007 ,

If you need to serve several domains for one site, you will need to update your NGINX configuration manually.
The [NGinx conf is mounted to nginx docker container](https://github.com/Monogramm/docker-erpnext/blob/master/docker-nginx.conf), ie. it is not Frappe that generates the configuration (at least right now).
