### ISSUE TITLE
[BUG] ERPNext Setup with Debian image failed

### ISSUE THREAD

**Issue by chhein** [Monogramm/docker-erpnext#32]
**Describe the bug**
Setup Wizard:
**Setup failed**
_Could not start up: Error in setup_
**To Reproduce**
1. Install like in description
2. Use Debian image - all versions from 12.0 to 13.0 are affected (!)
3. docker-compose up -d 
4. Follow wizard on the page
5. Error in logs raise up a

Provide Docker commands or docker-compose file if possible.

**Expected behavior**
Setup finishes normaly

**Stack trace**
If applicable, add stack trace using `docker logs` or `docker-compose logs` to identify the problem.
```
erpnext_app               | [2020-05-03 16:23:57 +0200] [664] [CRITICAL] WORKER TIMEOUT (pid:671)
erpnext_app               | [2020-05-03 16:23:57 +0200] [671] [ERROR] Error handling request /api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
erpnext_app               |     response = frappe.api.handle()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
erpnext_app               |     return frappe.handler.handle()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
erpnext_app               |     data = execute_cmd(cmd)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
erpnext_app               |     return frappe.call(method, **frappe.form_dict)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1051, in call
erpnext_app               |     return fn(*args, **newargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 71, in setup_complete
erpnext_app               |     task.get('fn')(task.get('args'))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 95, in setup_company
erpnext_app               |     fixtures.install_company(args)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py", line 395, in install_company
erpnext_app               |     make_records(records)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 384, in make_records
erpnext_app               |     doc.insert(ignore_permissions=True)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
erpnext_app               |     self.run_post_save_methods()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 926, in run_post_save_methods
erpnext_app               |     self.run_method("on_update")
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 794, in run_method
erpnext_app               |     out = Document.hook(fn)(self, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1065, in composer
erpnext_app               |     return composed(self, method, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in runner
erpnext_app               |     add_to_return_value(self, fn(self, *args, **kwargs))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 788, in <lambda>
erpnext_app               |     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 103, in on_update
erpnext_app               |     self.create_default_accounts()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/company/company.py", line 154, in create_default_accounts
erpnext_app               |     create_charts(self.name, self.chart_of_accounts, self.existing_company)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 61, in create_charts
erpnext_app               |     _import_accounts(chart, None, None, root_account=True)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 56, in _import_accounts
erpnext_web               | 92.211.132.152 - - [03/May/2020:16:23:57 +0200] "POST /api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete HTTP/1.1" 500 141 "http://mydomain.com/desk" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" "-"
erpnext_app               |     _import_accounts(child, account.name, root_type)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 56, in _import_accounts
erpnext_app               |     _import_accounts(child, account.name, root_type)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 56, in _import_accounts
erpnext_app               |     _import_accounts(child, account.name, root_type)
erpnext_app               |   [Previous line repeated 1 more time]
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 52, in _import_accounts
erpnext_app               |     account.insert()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 254, in insert
erpnext_app               |     self.run_method("after_insert")
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 794, in run_method
erpnext_app               |     out = Document.hook(fn)(self, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1065, in composer
erpnext_app               |     return composed(self, method, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1050, in runner
erpnext_app               |     add_to_return_value(self, f(self, method, *args, **kwargs))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/cache_manager.py", line 133, in build_table_count_cache
erpnext_app               |     }, as_dict=1)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 932, in multisql
erpnext_app               |     return self.sql(query, values, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
erpnext_app               |     self._cursor.execute(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
erpnext_app               |     result = self._query(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
erpnext_app               |     conn.query(q)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
erpnext_app               |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
erpnext_app               |     result.read()
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
erpnext_app               |     first_packet = self.connection._read_packet()
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
erpnext_app               |     packet_header = self._read_bytes(4)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 691, in _read_bytes
erpnext_app               |     data = self._rfile.read(num_bytes)
erpnext_app               |   File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
erpnext_app               |     return self._sock.recv_into(b)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 202, in handle_abort
erpnext_app               |     sys.exit(1)
erpnext_app               | SystemExit: 1
erpnext_app               | 
erpnext_app               | During handling of the above exception, another exception occurred:
erpnext_app               | 
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
erpnext_app               |     self.handle_request(listener, req, client, addr)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
erpnext_app               |     respiter = self.wsgi(environ, resp.start_response)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
erpnext_app               |     return ClosingIterator(app(environ, start_response), self.cleanup)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
erpnext_app               |     resp = f(*args[:-2] + (request,))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 88, in application
erpnext_app               |     frappe.db.rollback()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 753, in rollback
erpnext_app               |     self.sql("rollback")
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
erpnext_app               |     self._cursor.execute(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
erpnext_app               |     result = self._query(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
erpnext_app               |     conn.query(q)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
erpnext_app               |     self._execute_command(COMMAND.COM_QUERY, sql)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 750, in _execute_command
erpnext_app               |     raise err.InterfaceError("(0, '')")
erpnext_app               | pymysql.err.InterfaceError: (0, '')
erpnext_app               | [2020-05-03 16:23:57 +0200] [671] [INFO] Worker exiting (pid: 671)
erpnext_db                | 2020-05-03 14:23:57 57 [Warning] Aborted connection 57 to db: 'erpnext' user: 'erpnext' host: '172.18.0.6' (Got an error reading communication packets)

```
**Docker (please complete the following information):**
docker-compose version 1.17.1
Docker version 19.03.8, build afacb8b7f0

**Comment by madmath03** [comment]
Hi @chhein ,

From what I see, the error here is just due to a timeout of the background worker:
```
erpnext_app               | [2020-05-03 16:23:57 +0200] [664] [CRITICAL] WORKER TIMEOUT (pid:671)
```

We can increase the default value but this largely depends on the applications bundled with ERPNext and the power of your host so it's impossible to satisfy everyone.

In the meantime, you can simply increase the Gunicorn timeout for the background workers by setting `DOCKER_GUNICORN_TIMEOUT` (default to 120 seconds).

See [Docker Frappe configuration](https://github.com/Monogramm/docker-frappe#docker-entrypoint-configuration) for more details.

**Comment by chhein** [comment]
Thank you for your advices.
I tried it with 
DOCKER_GUNICORN_TIMEOUT=960 then with
DOCKER_GUNICORN_TIMEOUT=2000
I got in both cases the same error.

After that, i rescaled my Cloud Server to 8 dedicated cores with 32 GB RAM and tried it again.
Same error, doesnt work. And even on my local AMD Ryzen Machine, it doesnt work and the same error came up.

I also tried to use the Alpine-PostgreSQL Image, in one case i got the discribed error (missing column).

**Comment by madmath03** [comment]
That's weird... We've been able to reproduce your original issue on ERPNext 12 but increasing `DOCKER_GUNICORN_TIMEOUT` solved the issue.
Are you sure you have the same error in logs after increasing Gunicorn timeout ? Can you check your JavaScript console logs and network logs as well ?

One other thing that needs to be checked is your NGinx timeout config:
https://github.com/Monogramm/docker-erpnext/blob/efb5805673ab704b1934e3ea8f43fd8efdcc7e79/images/12.6/debian/nginx.conf#L47

If this is NGinx that times out, you should not have the error in the docker logs, but that would still display an error in the setup if it takes too long.
You can try increasing it as well.

We're going to increase both of those default values in next update of the docker containers: #31

**Comment by chhein** [comment]
Ive used a fresh clone of the repo
and used version 12.7-debian
and set
`DOCKER_GUNICORN_TIMEOUT=960` in .env 
and even
`export DOCKER_GUNICORN_TIMEOUT=960`
then in nginx.conf
` proxy_read_timeout 960; `

Still the same error and no luck.

**docker-compose logs -f** 
`erpnext_app               | [2020-05-05 11:05:03 +0200] [839] [INFO] Booting worker with pid: 839
erpnext_app               | [2020-05-05 11:05:04 +0200] [809] [CRITICAL] WORKER TIMEOUT (pid:819)
erpnext_db                | 2020-05-05  9:05:04 64 [Warning] Aborted connection 64 to db: 'erpnext' user: 'erpnext' host: '172.19.0.6' (Got an error reading communication packets)
erpnext_app               | [2020-05-05 11:05:04 +0200] [819] [ERROR] Error handling request /api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
erpnext_app               |     response = frappe.api.handle()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
erpnext_app               |     return frappe.handler.handle()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
erpnext_app               |     data = execute_cmd(cmd)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
erpnext_web               | 213.188.105.122 - - [05/May/2020:11:05:04 +0200] "POST /api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete HTTP/1.1" 500 141 "http://mydomain.com/desk" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" "-"
erpnext_app               |     return frappe.call(method, **frappe.form_dict)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1051, in call
erpnext_app               |     return fn(*args, **newargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 71, in setup_complete
erpnext_app               |     task.get('fn')(task.get('args'))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/setup_wizard.py", line 92, in stage_fixtures
erpnext_app               |     fixtures.install(args.get('country'))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py", line 276, in install
erpnext_app               |     set_more_defaults()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py", line 296, in set_more_defaults
erpnext_app               |     add_uom_data()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py", line 344, in add_uom_data
erpnext_app               |     }).insert(ignore_permissions=True)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 254, in insert
erpnext_app               |     self.run_method("after_insert")
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 794, in run_method
erpnext_app               |     out = Document.hook(fn)(self, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1065, in composer
erpnext_app               |     return composed(self, method, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1050, in runner
erpnext_app               |     add_to_return_value(self, f(self, method, *args, **kwargs))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/cache_manager.py", line 133, in build_table_count_cache
erpnext_app               |     }, as_dict=1)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 932, in multisql
erpnext_app               |     return self.sql(query, values, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
erpnext_app               |     self._cursor.execute(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
erpnext_app               |     result = self._query(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
erpnext_app               |     conn.query(q)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
erpnext_app               |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
erpnext_app               |     result.read()
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
erpnext_app               |     first_packet = self.connection._read_packet()
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
erpnext_app               |     packet_header = self._read_bytes(4)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 691, in _read_bytes
erpnext_app               |     data = self._rfile.read(num_bytes)
erpnext_app               |   File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
erpnext_app               |     return self._sock.recv_into(b)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 202, in handle_abort
erpnext_app               |     sys.exit(1)
erpnext_app               | SystemExit: 1
erpnext_app               | 
erpnext_app               | During handling of the above exception, another exception occurred:
erpnext_app               | 
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
erpnext_app               |     self.handle_request(listener, req, client, addr)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
erpnext_app               |     respiter = self.wsgi(environ, resp.start_response)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
erpnext_app               |     return ClosingIterator(app(environ, start_response), self.cleanup)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
erpnext_app               |     resp = f(*args[:-2] + (request,))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 88, in application
erpnext_app               |     frappe.db.rollback()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 753, in rollback
erpnext_app               |     self.sql("rollback")
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
erpnext_app               |     self._cursor.execute(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
erpnext_app               |     result = self._query(query)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
erpnext_app               |     conn.query(q)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
erpnext_app               |     self._execute_command(COMMAND.COM_QUERY, sql)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 750, in _execute_command
erpnext_app               |     raise err.InterfaceError("(0, '')")
erpnext_app               | pymysql.err.InterfaceError: (0, '')
erpnext_app               | [2020-05-05 11:05:04 +0200] [819] [INFO] Worker exiting (pid: 819)
erpnext_app               | [2020-05-05 11:05:04 +0200] [840] [INFO] Booting worker with pid: 840
`
**jS Console Log**
```
======== arguments ======== desk.min.js:1:61772
Object { coa: "SKR04 mit Kontonummern", bank_account: "MyBank" }
desk.min.js:1:61815
======== desk.min.js:1:61835
method:erpnext.accounts.doctype.account.chart_of_accounts.chart_of_accounts.validate_bank_account desk.min.js:1:61911
======== response ======== desk.min.js:1:61928
Object { message: false }
desk.min.js:1:61995
======== desk.min.js:1:62010
Unable to handle failed response desk.min.js:1:60520
console.trace() SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
    report_error http://mydomain.com/assets/js/desk.min.js?ver=1588669110.0:1
    500 http://mydomain.com/assets/js/desk.min.js?ver=1588669110.0:1
    call http://mydomain.com/assets/js/desk.min.js?ver=1588669110.0:1
    jQuery 4
desk.min.js:1:60568
    call http://mydomain.com/assets/js/desk.min.js?ver=1588669110.0:1
    jQuery 4
```

​

**Comment by madmath03** [comment]
> Ive used a fresh clone of the repo
> and used version 12.7-debian
> and set
> `DOCKER_GUNICORN_TIMEOUT=960` in .env
> and even
> `export DOCKER_GUNICORN_TIMEOUT=960`
> then in nginx.conf
> `proxy_read_timeout 960;`

Okay, that explains why it's not working: you need to set this in the docker-compose.yml, otherwise it's not going to be used by the app container.
Look at our in progress develop branch docker-compose for example:
https://github.com/Monogramm/docker-erpnext/blob/2107a3cf532b491ead5cbfc4e1bc57c446c23ba4/template/docker-compose_mariadb.yml#L36-L55

**Comment by chhein** [comment]
> > Ive used a fresh clone of the repo
> > and used version 12.7-debian
> > and set
> > `DOCKER_GUNICORN_TIMEOUT=960` in .env
> > and even
> > `export DOCKER_GUNICORN_TIMEOUT=960`
> > then in nginx.conf
> > `proxy_read_timeout 960;`
> 
> Okay, that explains why it's not working: you need to set this in the docker-compose.yml, otherwise it's not going to be used by the app container.
> Look at our in progress develop branch docker-compose for example:
> 
> https://github.com/Monogramm/docker-erpnext/blob/2107a3cf532b491ead5cbfc4e1bc57c446c23ba4/template/docker-compose_mariadb.yml#L36-L55
`   environment: 
     # Docker setup 
     - DOCKER_DB_ALLOWED_HOSTS=172.%.%.% 
     - DOCKER_GUNICORN_TIMEOUT=600 `

Thank you very much, this does the Job !
