### ISSUE TITLE
Database error Alpine Image

### ISSUE THREAD

**Issue by dreamneupane** [Monogramm/docker-erpnext#36]
I got following error  inside erpnext_app container... i am using alpine v 13 image ... Can you please suggest why?

Updating mariadDB users allowed hosts ...
ERROR 1356 at line 1 ; View 'mysql.user' references invalid tables(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

**Comment by madmath03** [comment]
The `DOCKER_DB_ALLOWED_HOSTS` was a hack to ensure that ERPNext has access to MariaDB but it seems to not be needed anymore.
You can just remove it from your docker-compose and it should work as expected.
