### ISSUE TITLE
Authentication error after installing

### ISSUE THREAD

**Issue by oko-x** [Monogramm/docker-erpnext#38]
Hi,

immediately after the installation I get Internal Server Error in the app:

> erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
erpnext_app               |     self.handle_request(listener, req, client, addr)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
erpnext_app               |     respiter = self.wsgi(environ, resp.start_response)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
erpnext_app               |     return ClosingIterator(app(environ, start_response), self.cleanup)
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
erpnext_app               |     resp = f(*args[:-2] + (request,))
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 85, in application
erpnext_app               |     response = handle_exception(e)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 212, in handle_exception
erpnext_app               |     http_status_code=http_status_code)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 35, in render
erpnext_app               |     raise_if_disabled(path)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 371, in raise_if_disabled
erpnext_app               |     'route': ['like', '%{0}'.format(path)]
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 535, in get_all
erpnext_app               |     return frappe.get_all(*args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1349, in get_all
erpnext_app               |     return get_list(doctype, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1322, in get_list
erpnext_app               |     return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 96, in execute
erpnext_app               |     result = self.build_and_run()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
erpnext_app               |     args = self.prepare_args()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
erpnext_app               |     self.set_optional_columns()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
erpnext_app               |     columns = get_table_columns(self.doctype)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
erpnext_app               |     return frappe.db.get_table_columns(doctype)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 879, in get_table_columns
erpnext_app               |     columns = self.get_db_table_columns('tab' + doctype)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 870, in get_db_table_columns
erpnext_app               |     where table_name = %s ''', table)]
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 104, in sql
erpnext_app               |     return super(PostgresDatabase, self).sql(*args, **kwargs)
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
erpnext_app               |     self.connect()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
erpnext_app               |     self._conn = self.get_connection()
erpnext_app               |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 70, in get_connection
erpnext_app               |     self.host, self.user, self.user, self.password, self.port
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
erpnext_app               |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
erpnext_app               | psycopg2.OperationalError: FATAL:  password authentication failed for user "erpnext"

**Comment by madmath03** [comment]
Hello @oko-x 

Please use the issue template, too many unanswered questions to properly help you

**Comment by mmangione** [comment]
The issue here is in the pg_hba.conf file in the PostgreSQL server.

Add the line:
`host    all             all             172.0.0.0/8         md5`

before the end of the file and restart
