### ISSUE TITLE
«Sorry! We will be back soon.» after install

### ISSUE THREAD

**Issue by bobcodev** [Monogramm/docker-erpnext#43]
Several times built an image with various yml with default settings - the result is the same, on the lettering page:

> **Sorry!
> We will be back soon.**
> 
> Don't panic. It's not you, it's us.
> Most likely, our engineers are updating the code, and it should take a minute for the new code to load into memory.
> 
> Try refreshing after a minute or two.

I suspect it is associated with variables in .env or the configuration of nginx. Help me please.

**Comment by madmath03** [comment]
Hi @bobcodev 

Please report issues using the provided template, in particular the state and logs of the docker containers.

**Comment by bobcodev** [comment]
Thank you, @ MadMath03, for your answer. My question concerned the available of ERPNext in LAN (https://discuss.erpnext.com/t/how-can-i-make-erp-available-in-lan-deployed-with-docker/65392/18). I found a discussion on the forum, but I postponed the solution to the problem, since I installed the ERP locally.
