### ISSUE TITLE
Custom app & Multi tenancy?

### ISSUE THREAD

**Issue by bobcodev** [Monogramm/docker-erpnext#44]
As far as I understand, the solution does not support custom app and a multi tenancy? Will support in the future?

**Comment by madmath03** [comment]
As mentioned in the README, the current architecture supports custom apps by simply creating a new docker image expanding this one: "_Check image [Monogramm/docker-erpnext-ext](https://github.com/Monogramm/docker-erpnext-ext) to see how to expand this image and add custom frappe apps._"

This image does not support multi tenancy out of the box, but you could in theory (not tested) update the `sites/common_site_config.json` to only contain shared information and then use `bench` commands to create new sites.
It is not currently not on our roadmap to manage this automatically.
