### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by clefavelli** [Monogramm/docker-erpnext#9]
I cant install your sample because I cant tell the installation sequence

A clear and concise description of an installation sequence will be really helpful.

**Comment by madmath03** [comment]
Hi,

The installation is actually pretty straightforward : select the version you want in the images folder, run the docker-compose with `docker-compose up -d` and that's it.

You should take a look at the Travis CI test suite https://github.com/Monogramm/docker-erpnext/blob/master/.travis.yml : the automated tests do not only check that the Docker image builds properly, it also check that it runs.
You can look at the Travis CI runs and logs ([link](https://travis-ci.org/Monogramm/docker-erpnext) at the top of the README) to see the installation sequence.

Let me know if you have another issue or if I misunderstood your point.

**Comment by clefavelli** [comment]
> Hi,
> 
> The installation is actually pretty straightforward : select the version you want in the images folder, run the docker-compose with `docker-compose up -d` and that's it.
> 
> You should take a look at the Travis CI test suite https://github.com/Monogramm/docker-erpnext/blob/master/.travis.yml : the automated tests do not only check that the Docker image builds properly, it also check that it runs.
> You can look at the Travis CI runs and logs ([link](https://travis-ci.org/Monogramm/docker-erpnext) at the top of the README) to see the installation sequence.
> 
> Let me know if you have another issue or if I misunderstood your point.

Hi, mine freezes here :

_Building erpnext_app
Step 1/5 : FROM monogramm/docker-frappe:11-alpine
 ---> 919653b56cb1
Step 2/5 : LABEL maintainer "Monogramm Maintainers <opensource at monogramm dot io>"
 ---> Using cache
 ---> 94a1b2672180
Step 3/5 : ENV ERPNEXT_BRANCH v11.1.46
 ---> Using cache
 ---> 7724a4539d36
Step 4/5 : RUN set -ex;     bench get-app --branch $ERPNEXT_BRANCH erpnext https://github.com/frappe/erpnext;     sudo ./env/bin/pip3 install         ldap3     ;
 ---> Running in 5fc8a0f56fb8

+ bench get-app --branch v11.1.46 erpnext https://github.com/frappe/erpnext
INFO:bench.app:getting app erpnext
INFO:bench.utils:git clone https://github.com/frappe/erpnext --branch v11.1.46 --depth 1 --origin upstream
Cloning into 'erpnext'...
Note: checking out '9a858a98246a88e441bcc399f2e2a8f99892fa4d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (5276/5276), done.
INFO:bench.app:installing erpnext
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext_ 


Am installing on a digital ocean centos7 environment.

**Comment by madmath03** [comment]
I see that you are using Alpine variant.
Alpine is great for its improved security and performance (smaller image) but building containers for alpine almost always takes more time, and ERPNext is extremely slow to retrieve on Alpine : if you look at Travis CI build results, it takes [28 minutes to get ERPNext on Alpine](https://travis-ci.org/Monogramm/docker-erpnext/jobs/557793376#L498), while it takes only [2 minutes on Debian](https://travis-ci.org/Monogramm/docker-erpnext/jobs/557793377#L498)... and I have no idea why it's so slow 😅 

If you're fine with using the default content of our images (ie. no need to add any apps), I suggest you update the docker-compose to use our prebuilt images from DockerHub:
* replace every occurrence of `build: ./` with `image: monogramm/docker-erpnext:11-alpine`
* run the docker-compose with `docker-compose up -d`

I will probably update the docker-compose, add some comments, to help use prebuilt images.

**Comment by clefavelli** [comment]
Okay I have managed to run the 11.1 version using docker-compose up -d

Running docker ps i get the following :
[root@prenus alpine]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
73cb113dfe34        redis:alpine        "docker-entrypoint..."   27 seconds ago      Up 23 seconds       6379/tcp            erpnext_redis_queue
af05875228c2        redis:alpine        "docker-entrypoint..."   27 seconds ago      Up 24 seconds       6379/tcp            erpnext_redis_socketio


Am looking for the running app and perhaps an image with open ports to point my browser to but only the redis containers are running. Where is the erpnext app?

**Comment by madmath03** [comment]
You should use `docker-compose ps` instead to get the status of all the containers listed in your docker-compose.
If you only see the redis containers, it means the others crashed and you need to find out why.

Once you have found the reason of the crash and fixed it, there is a nginx container exposing ERPNext at http://localhost:80.

I added comments and simple doc in README about this so closing this issue.
